### ISSUE TITLE
5.38.0.2 fails to build XS-libpanda-1.5.10 with gcc 13

### ISSUE THREAD

**Issue by mimmo-m** [StrawberryPerl/Perl-Dist-Strawberry#137] opened 2023-09-18 10:55 UTC
Works with strawberry 5.32.1 on windows
Works with gcc 12.3.0 under linux but not with gcc 13.2.0

**Comment by shawnlaffan** [comment] 2023-09-18 22:19
It seems from your comment that this problem is not with Strawberry Perl, as it applies to gcc-13 across platforms?  

If so then the issue should be reported to the XS::libpanda issue tracker, although it seems this has already been done:  https://rt.cpan.org/Public/Bug/Display.html?id=149073

FWIW, I get build failures with the XS::libcatch dependency due to incorrect paths being used (my portable perls have been moved and something is using the previous path).  I have not yet tracked them down.

**Comment by mimmo-m** [comment] 2023-09-19 07:52
Hello,
the issue is with Strawberry (I tested with your test release 5.38.02) and gcc 13 (you include in your distribution).
To exclude issues introduced by me I also checked on linux with gcc 13.2.0 (redhat and slackware) and XS::libpanda failed to build/.
On linux gcc 12.3.0 works fine.
From my limited knowledge I guess the problem is due to some syntax change introduced by gcc.

Yes I submitted https://rt.cpan.org/Public/Bug/Display.html?id=149073 but, since I get the same issue on linux, it is not a problem of paths.

I have tried to build strawberry with gcc 12.3 but I couldn't (also, but not only, because I have not enough time to dedicate).
Is there any suggestions you can give to reproduce the full build from scratch (excluding gcc)?
I got stuck when building libraries.

Many thanks,
Regards

**Comment by shawnlaffan** [comment] 2023-09-19 08:33
Thanks for the additional details.  However, the fact that the issue is related to gcc-13 means it needs to be fixed by the maintainers of XS-libpanda.  

In terms of building with gcc-12, have a look at https://github.com/StrawberryPerl/spbuild to get started.  If you don't ned the external libs then you can build a perl directly.  See for example https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/39#issuecomment-1181826988

**Comment by shawnlaffan** [comment] 2023-09-19 09:32
Thanks @sisyphus 

SP 5.38 did not use any specific patches but the changed defines can be seen at https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/427b95661366260b251015a2fb90fd2745aa0cbb/share/64bit-5.38.0.1.pp#L59-L79

These are applied using code within the build system but can be done by hand pretty easily when not using an automated system.

**Comment by sisyphus** [comment] 2023-09-19 11:11
> SP 5.38 did not use any specific patches ...

Duh ... yeah, just my fried brain ...IIRC, it was 5.36.1 that was the recent stable release needing patching.
Sorry.

Cheers,
Rob

**Comment by sisyphus** [comment] 2023-09-19 14:15
@mimmo-m, it turns out that the dreaded <code>__CRT_UUID_DECL</code> has been backported to gcc-12.3.0, and the XS::libpanda build therefore fails in the same way. (I actually tested that.)
So,  I tried the 12.2.0 compiler next.
```
gcc version 12.2.0 (MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders)
```
In the perl-5.38.0 source, I cd to the <code>win32</code> folder and run:
```
gmake USE_QUADMATH=define I_QUADMATH=define CCHOME=C:\winlibs-gcc-1220\mingw64 CCTYPE=GCC USE_MINGW_ANSI_STDIO=define SKIP_CCHOME_CHECK=1 BUILDOPTEXTRA=-fdiagnostics-color=never INST_TOP=C:\perl-5.38.0-1220-q -j8 test
```
If you don't want a quadmath build, you can remove  the "USE_QUADMATH" and "I_QUADMATH" args. (I personally think it's dumb to accept a perl with an nvtype of <code>double</code> when one can just as easily have a perl with an nvtype of <code>__float128</code>.)
The BUILDOPTEXTRA argument is also optional.
You'll need to modify the CCHOME argument to point to your gcc installation. (Note that it specifies the folder that <b>*contains*</b> the "bin" folder.)
Set INST_TOP to the location you want perl to go into.
All tests pass for me.

Next I install perl by running the exact same command - except that I replace "test" (at the end of the command) with "install".

Then insert this perl at the beginning of the PATH:
```
set PATH=C:\perl-5.38.0-1220-q\bin;%PATH%
```
Then run <code>cpan -i XS::libpanda</code>
XS::libpanda failed a couple of tests:
```
Test Summary Report
-------------------
t/log/log.t          (Wstat: 1280 (exited 5) Tests: 0 Failed: 0)
  Non-zero exit status: 5
  Parse errors: No plan found in TAP output
t/log/module.t       (Wstat: 1280 (exited 5) Tests: 1 Failed: 0)
  Non-zero exit status: 5
  Parse errors: No plan found in TAP output
Files=24, Tests=142, 11 wallclock secs ( 0.11 usr +  0.02 sys =  0.13 CPU)
Result: FAIL
Failed 2/24 test programs. 0/142 subtests failed.
make.EXE: *** [Makefile:961: test_dynamic] Error 255
  SYBER/XS-libpanda-1.5.10.tar.gz
  C:\make\bin\make.EXE test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports SYBER/XS-libpanda-1.5.10.tar.gz
```
Maybe it's just a missing logging capability - though a preliminary investigation indicates that something is segfaulting.
Rather than investigate any further, I just force installed XS::libpanda by running <code>cpan -fi XS::libpanda</code>

Let me know if you give that a try and it doesn't work for you.

Cheers,
Rob

**Comment by sisyphus** [comment] 2023-09-20 02:07
> You might need to raise this with the mingw-w64 people.

Correction: It's actually up to the maintainers of panda to fix the source in a portable way.

Here is a simple patch (hack) to XS-libpanda-1.5.10/clib/src/panda/win/exception_debug.cc that will allow XS::libpanda to build with mingwrt-11 - by simply commenting out the offending  \#ifdef/\#else/\#endif block of code:
```
--- ../XS-libpanda-1.5.10-9/clib/src/panda/win/exception_debug.cc       2022-04-12 00:33:54.000000000 +1000
+++ clib/src/panda/win/exception_debug.cc       2023-09-20 11:41:58.173708500 +1000
@@ -2,7 +2,7 @@
 #include "exception_debug.h"
 #include <windows.h>
 #include <dbgeng.h>
-
+/*
 #ifdef __CRT_UUID_DECL // for __MINGW32__
     __CRT_UUID_DECL(IDebugClient,0x27fe5639,0x8407,0x4f47,0x83,0x64,0xee,0x11,0x8f,0xb0,0x8a,0xc8)
     __CRT_UUID_DECL(IDebugControl,0x5182e668,0x105e,0x416e,0xad,0x92,0x24,0xef,0x80,0x04,0x24,0xba)
@@ -12,7 +12,7 @@
     DEFINE_GUID(IID_IDebugControl,0x5182e668,0x105e,0x416e,0xad,0x92,0x24,0xef,0x80,0x04,0x24,0xba);
     DEFINE_GUID(IID_IDebugSymbols,0x8c31e98c,0x983a,0x48a5,0x90,0x16,0x6f,0xe5,0xd6,0x67,0xa9,0x50);
 #endif
-
+*/
 using namespace panda;

 com_global_initer::com_global_initer() noexcept : _ok{false} {
```

When I get the time to run the checks I'll update this post with a portable patch to panda/win/exception_debug.cc.
(Or maybe someone else will do that for me ;-)

Note: t/log/log.t and t/log/module.t still fail for me.

Cheers,
Rob

**Comment by sisyphus** [comment] 2023-09-20 11:56
As regards a portable patch that enables the building of XS-libpanda-1.5.10, this seems fine:
```
--- clib/src/panda/win/exception_debug.cc_orig  2022-04-12 00:33:54.000000000 +1000
+++ clib/src/panda/win/exception_debug.cc       2023-09-20 21:42:54.264834500 +1000
@@ -3,6 +3,7 @@
 #include <windows.h>
 #include <dbgeng.h>

+#if __MINGW64_VERSION_MAJOR < 11
 #ifdef __CRT_UUID_DECL // for __MINGW32__
     __CRT_UUID_DECL(IDebugClient,0x27fe5639,0x8407,0x4f47,0x83,0x64,0xee,0x11,0x8f,0xb0,0x8a,0xc8)
     __CRT_UUID_DECL(IDebugControl,0x5182e668,0x105e,0x416e,0xad,0x92,0x24,0xef,0x80,0x04,0x24,0xba)
@@ -12,6 +13,7 @@
     DEFINE_GUID(IID_IDebugControl,0x5182e668,0x105e,0x416e,0xad,0x92,0x24,0xef,0x80,0x04,0x24,0xba);
     DEFINE_GUID(IID_IDebugSymbols,0x8c31e98c,0x983a,0x48a5,0x90,0x16,0x6f,0xe5,0xd6,0x67,0xa9,0x50);
 #endif
+#endif

 using namespace panda;
```
Tested against against the following 64-bit builds:
perl-5.39.2, built by gcc-13.2.0 (mingwrt 11)
perl-5.38.0, built by gcc-13.1.0 (mingwrt 11)
perl-5.38.0, built by gcc-12.3.0 (mingwrt 11)
perl-5.38.0, built by gcc-12.2.0 (mingwrt 10)
perl-5.36.0, built by gcc-11.3.0 (mingwrt 10)
perl-5.32.1, built by gcc-8.3.0 (mingwrt 6 )

And also tested against the following 32-bit (64-bit integer) builds:
perl-5.38.0, built by gcc-13.1.0 (mingwrt 11)
perl-5.36.0, built by gcc-11.3.0 (mingwrt 10)
perl-5.32.1, built by gcc-8.3.0 (mingwrt 6)

Except for the 5.32.1 builds, I find that t/log/log.t and t/log/module.t fail.
I noticed also that my 32-bit build of perl-5.36.1 failed t/log/logger.t. (Perhaps there are other perls that failed that same test script and I didn't notice at the time.)

With those builds of XS-libpanda-1.5.10 that failed those logging tests, I saw the following 
```
....
[ 75%] Building CXX object D:/s/XS-libpanda-1.5.10/clib/build/CMakeFiles/panda-lib-tests.dir/tests/string_char.cc.obj
D:/s/XS-libpanda-1.5.10/clib/tests/string_char.cc: In function 'void test_compilation_warnings()':
D:/s/XS-libpanda-1.5.10/clib/tests/string_char.cc:10:76: warning: 'abc' may be used uninitialized [-Wmaybe-uninitialized]
   10 |         auto data = string("\x05\x01\x00\x01") + string((char*)&abc, 16) + string((char*)&abc, 2);
      |                                                                            ^~~~~~~~~~~~~~~~~~~~~~
In file included from D:/s/XS-libpanda-1.5.10/clib/src/panda/string.h:2,
                 from D:/s/XS-libpanda-1.5.10/clib/tests/test.h:3,
                 from D:/s/XS-libpanda-1.5.10/clib/tests/string_test.h:2,
                 from D:/s/XS-libpanda-1.5.10/clib/tests/string_char.cc:1:
D:/s/XS-libpanda-1.5.10/clib/src/panda/basic_string.h:209:5: note: by argument 2 of type 'const char*' to 'panda::basic_string<CharT, Traits, Alloc>::basic_string(const CharT*, panda::basic_string<CharT, Traits, Alloc>::size_type) [with CharT = char; Traits = std::char_traits<char>; Alloc = panda::DefaultStaticAllocator<char>]' declared here
  209 |     basic_string (const CharT* str, size_type len) : _length(len) {
      |     ^~~~~~~~~~~~
D:/s/XS-libpanda-1.5.10/clib/tests/string_char.cc:9:11: note: 'abc' declared here
    9 |         } abc;
      |           ^~~
[ 77%] Building CXX object D:/s/XS-libpanda-1.5.10/clib/build/CMakeFiles/panda-lib-tests.dir/tests/string_char16.cc.obj
....
```
With 5.32.1 (which passed all tests) there were no warnings issued.
Perhaps those warnings are related to those test failures.

Cheers,
Rob

**Comment by mimmo-m** [comment] 2023-09-20 12:47
@sisyphus I will test your patch
To summarize I have:
winlibs gcc12.3.0 -->error
linux    gcc1230  --> OK
winlibs gcc1320  --> error
linux    gcc1320  --> error
Mimmo

**Comment by mimmo-m** [comment] 2023-09-23 10:43
@sisyphus Hello, your patch works also for me.
gcc 13 (win32 and linux) does not compile the **Date** module, I will open a bug to the developer.
I have hacked the 5.38.0.2 using winlibs_gcc12.2.0, it works for those who need **win32+perl5.38+Date**.
Cheers,
Mimmo

**Comment by sisyphus** [comment] 2023-09-23 12:09
The first problem I see with Date-5.2.12 is that the prerequisite XS-Framework-1.5.5 fails a couple of tests.
I get around that by running <code>cpan -fi XS::Framework</code>.

However, Date-5.2.12 then fails to compile:
```
gmake[1]: Entering directory 'D:/s/Date-5.2.12/clib/cmake_props'
[  9%] Building CXX object D:/s/Date-5.2.12/clib/build/CMakeFiles/panda-date.dir/src/panda/date/Date.cc.obj
In file included from D:/s/Date-5.2.12/clib/src/panda/date/Date.h:2,
                 from D:/s/Date-5.2.12/clib/src/panda/date/Date.cc:1:
D:/s/Date-5.2.12/clib/src/panda/date/error.h:6:6: warning: elaborated-type-specifier for a scoped enum must not use the 'class' keyword
    6 | enum class errc : uint8_t {
      | ~~~~ ^~~~~
      |      -----
D:/s/Date-5.2.12/clib/src/panda/date/error.h:6:17: error: found ':' in nested-name-specifier, expected '::'
    6 | enum class errc : uint8_t {
      |                 ^
      |                 ::
 .... [more errors follow]
```
When <code>C++</code> code gets involved, I quickly lose interest ;-)

Cheers,
Rob

**Comment by mimmo-m** [comment] 2023-09-23 16:08
In this case I found a simple
`#include <cstdint>`
in `clib/src/panda/date/error.h`
solves all problems.

Cheers,
Mimmo

**Comment by shawnlaffan** [comment] 2023-09-23 22:36
There are likely many such cases in the wild.  

libgeos, for example, needed similar patching for gcc-13 when building it as an alien module.  
https://github.com/shawnlaffan/perl-alien-geos/commit/870bd9a3a2544d706be371875a376ca79158adf9

**Comment by sisyphus** [comment] 2023-09-24 11:09
> <code>#include \<cstdint\></code>

Yep - that works fine for me, too.

Cheers,
Rob

**Comment by shawnlaffan** [comment] 2023-10-05 00:48
This issue seems to be resolved now so I'll close it.  It can be re-opened if there are still things that need to be resolved.  Otherwise new topics can be raised under new issues.

**Closed by shawnlaffan** 2023-10-05 00:48 UTC
Labels: closable
