### ISSUE TITLE
Locale 'Korean_Korea.949' is unsupported, and may crash the interpreter.  with perl 5.38.0.1

### ISSUE THREAD

**Issue by aero** [StrawberryPerl/Perl-Dist-Strawberry#119] opened 2023-07-15 03:11 UTC
Hi
I tested with version 5.38.0.1 on windows 10 (cmd locale cp949).
I got the following locale related warning message.

```
C:\strawberry-perl-5.38.0.1-64bit-PDL>perl
Locale 'Korean_Korea.949' is unsupported, and may crash the interpreter.
```

**Comment by twata1** [comment] 2023-07-15 10:07
I believe that from now on we will set the environment variable LC_ALL.

example:
```
set LC_ALL=C
```

**Comment by shawnlaffan** [comment] 2023-07-16 11:09
I cannot reproduce this on my local machine.  

Do you have other env vars set that might influence this?  

```
C:\user\perls\5.38.0.1_PDL>chcp
Active code page: 437

C:\user\perls\5.38.0.1_PDL>chcp 949
Active code page: 949

C:\user\perls\5.38.0.1_PDL>perl
^D

C:\user\perls\5.38.0.1_PDL>perl -V | findstr uname
    uname='Win32 strawberry-perl 5.38.0.1 # 03:13:47 Wed July 05 2023 x64'
```

**Comment by aero** [comment] 2023-07-16 13:09
Here is my result.
```
C:\strawberry-perl-5.38.0.1-64bit-PDL>chcp
활성 코드 페이지: 949

C:\strawberry-perl-5.38.0.1-64bit-PDL>perl
Locale 'Korean_Korea.949' is unsupported, and may crash the interpreter.
^D

C:\strawberry-perl-5.38.0.1-64bit-PDL>perl -V | findstr uname
Locale 'Korean_Korea.949' is unsupported, and may crash the interpreter.
    uname='Win32 strawberry-perl 5.38.0.1 # 03:13:47 Wed July 05 2023 x64'
```
My system locale is
( https://www.tenforums.com/tutorials/132175-see-current-system-locale-windows-10-a.html )
```
PS C:\Users\owner> Get-WinSystemLocale

LCID             Name             DisplayName
----             ----             -----------
1042             ko-KR            한국어 (대한민국)
```

**Comment by shawnlaffan** [comment] 2023-07-16 21:43
Thanks for the extra details.  

I wonder if this is a knock-on effect of the stricter locale handling used in perl 5.38, or that the docker file is missing something needed for those changes.  See discussion in https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/97

**Comment by shawnlaffan** [comment] 2023-07-17 07:46
@aero - does this also occur with perl 5.36.1.1?

If it does then it would seem to be related to the build environment.  Otherwise it could be some interaction as noted in my previous comment.

**Comment by aero** [comment] 2023-07-17 13:17
@shawnlaffan 
No, 5.36.11 has no problem.
```
----------------------------------------------
 Welcome to Strawberry Perl Portable Edition!
 * URL - http://www.strawberryperl.com/
 * see README.TXT for more info
----------------------------------------------
Perl executable: C:\strawberry-perl-5.36.1.1-64bit-portable\perl\bin\perl.exe
Perl version   : 5.36.1 / MSWin32-x64-multi-thread

C:\strawberry-perl-5.36.1.1-64bit-portable>perl
^D

C:\strawberry-perl-5.36.1.1-64bit-portable>
```

**Comment by genio** [comment] 2023-07-17 13:24
https://github.com/Perl/perl5/commit/667fa5f07f977e11018489f79c0e6531c9f79a72 was pointed out to me on IRC

**Comment by shawnlaffan** [comment] 2023-07-17 22:01
I guess the question is whether we can do something at the Strawberry level so that builds can be used across code pages, or whether the fix needs to go into Perl itself.

In the 5.38.0 builds I have been setting ```LC_ALL=C``` before building (see #97).  I wonder if using ```chcp``` to set the code page will be a better mechanism?  Or something else?

We have also been seeing failures in some of the ```op/magic.t``` tests (#60) but these differ from those in https://github.com/Perl/perl5/issues/20373 and occur for both the 5.36 and 5.38 builds.

**Comment by blues1875** [comment] 2023-07-31 10:15
I am also seeing an error message related to locale with 5.38.0.1. Strangely, this only appears in the VS Code terminal window and not in a system cmd window:
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:       glish_
        LC_ALL = (unset),
        (possibly more locale environment variables)
        LANG = "en_US.UTF-8"                                 MSWin3
    are supported and installed on your system.
perl: warning: Falling back to the system default locale ("English_United Kingdom.1252").
```
This error doesn't occur under 5.36.1.1 either. My system locale is this:
```
LCID             Name             DisplayName
----             ----             -----------
1046             pt-BR            Portuguese (Brazil) 
```

**Comment by blues1875** [comment] 2023-07-31 13:23
Note that setting the environment variable `LC_ALL` to either `C` or `English_United Kingdom.1252` suppresses the error on my 
system, but setting it to `en_US.UTF-8` doesn't.

**Comment by shawnlaffan** [comment] 2023-07-31 21:46
Thanks @blues1875 

@genio - would it be worth checking in on IRC again?

**Comment by shawnlaffan** [comment] 2023-07-31 21:49
Although this has just been committed:
https://github.com/Perl/perl5/commit/f0eb8bbcea48a988acb7df5c3c3db93d4a67fb75

Commit message:
> Prior to this commit the locale handling code thought that Windows used
"" for the system default locale.  But it doesn't, and to get to this
point in the initialization code, the "" had already been tried and
failed.

**Comment by shawnlaffan** [comment] 2023-08-05 00:06
I suspect the docker image is missing locale information and this has a knock on effect with the builds.  

These commands are run in a fresh docker instance using the ```lstc2019``` image per the dockerfiles on the spbuild repo:
```
PS Z:\> cmd.exe
Microsoft Windows [Version 10.0.17763.4499]
(c) 2018 Microsoft Corporation. All rights reserved.

Z:\>chcp
Active code page: 0
```

There are also language tools under powershell but these require a more recent version of powershell, or need to be installed.
https://learn.microsoft.com/en-us/powershell/module/languagepackmanagement/?view=windowsserver2019-ps

These tools might be part of the more recent ```ltsc2022``` image but that won't run on my Windows 10 build machine.

If anyone has suggestions then please note them.

**Comment by shawnlaffan** [comment] 2023-08-05 05:38
I've just uploaded a portable version of Strawberry Perl 5.38.0.2, built on a local machine instead of under docker.  Hopefully this will avoid the locale problems reported in this issue.

@aero and @blues1875 - can you please test it?  (Others are of course welcome to test and report for their systems).

**Comment by aero** [comment] 2023-08-05 08:14
@shawnlaffan 
I got the same error message.
```
----------------------------------------------
 Welcome to Strawberry Perl Portable Edition!
 * URL - http://www.strawberryperl.com/
 * see README.TXT for more info
----------------------------------------------
Perl executable: C:\strawberry-perl-5.38.0.2-64bit-portable\perl\bin\perl.exe
Perl version   : 5.38.0 / MSWin32-x64-multi-thread

C:\strawberry-perl-5.38.0.2-64bit-portable>perl -e "print $]"
Locale 'Korean_Korea.949' is unsupported, and may crash the interpreter.
5.038000
C:\strawberry-perl-5.38.0.2-64bit-portable>
```

**Comment by sisyphus** [comment] 2023-08-05 08:47
I wonder if this could be a deficiency in the mingw-w64 toolchain.
It would be interesting to know if the same problem exists with perl-5.38.0 built using Visual Studio 2022.

It looks to me that I've already reported a locale-related deficiency that's specific to mingw-w64 at https://www.perlmonks.org/?node_id=11153468.
Maybe there are others ?

I also wonder whether @khw might be able to provide some assistance  with this.

Disclaimer: I'm not at all knowledgeable when it comes to matters concerning locales.

Cheers,
Rob

**Comment by shawnlaffan** [comment] 2023-08-05 08:53
Thanks for testing @aero.  

If I get a chance tomorrow then I'll try a build patched with the changes in https://github.com/Perl/perl5/commit/f0eb8bbcea48a988acb7df5c3c3db93d4a67fb75 (see main commit text above https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/119#issuecomment-1659233804)

There have been many locale changes since 5.39.0 so there are probably others that might be useful.

**Comment by sisyphus** [comment] 2023-08-05 09:00
> It would be interesting to know if the same problem exists with perl-5.38.0 built using Visual Studio 2022.

Duh ... I can probably help with that.
On my VS2022-built perl-5.38.0:
```
>perl -MPOSIX -wle "$loc = POSIX::setlocale( LC_ALL, 'Korean_Korea.949' ); print $loc;"
Locale 'Korean_Korea.949' is unsupported, and may crash the interpreter.
Korean_Korea.949
```
And on my mingw-w64-built perl-5.38.0:
```
>perl -MPOSIX -wle "$loc = POSIX::setlocale( LC_ALL, 'Korean_Korea.949' ); print $loc;"
Locale 'Korean_Korea.949' is unsupported, and may crash the interpreter.
Korean_Korea.949
```
Looks like it ain't specific to mingw-w64.

Cheers,
Rob

**Comment by blues1875** [comment] 2023-08-05 11:25
I can also confirm that 5.38.0.2 didn't change anything. I think my problem is a different one, though still related. It seems that VS Code introduced the default environment setting LANG=en_US.UTF-8 to the embedded terminal to fix someone's problem back in 2017. It seems a bit naive to assume that everyone has that locale installed on their system, but that was their fix then. There is a way to unset that environment variable in VS Code, which will fix my problem, but the fact that it only appeared now (after years of using perl and VS Code) may be significant.

**Comment by sisyphus** [comment] 2023-08-06 01:34
According to the perldiag documentation, this is a new warning, introduced in perl-5.38.0:
<c>
    Locale '%s' is unsupported, and may crash the interpreter.
        (S locale) The named locale is not supported by Perl, and using it
        leads to undefined behavior, including potentially crashing the
        computer.

        Currently the only locales that generate this severe warning are
        non-UTF-8 ones which have characters that require more than one byte
        to represent (common in older East Asian language locales). See
        perllocale.
</c>
I speculate that if this warning had been available to perl-5.36.0, then it would have emitted the same warning.
Furthermore, I speculate:
1) if a script doesn't crash the 5.36.0 interpreter, then it won't crash the 5.38.0 interpreter/computer;
2) if a script crashes the 5.38.0 interpreter, then it will also crash the 5.36.0 interpreter/computer.

Probably the best way to attract attention from the locale experts is to file an issue about this at https://github.com/Perl/perl5/issues.
I'm thinking the response will be that perl should *always* have emitted this warning - but I don't know.
If you've ventured (or potentially might inadvertently venture) into undefined territory, then I think perl should warn about it.

Cheers,
Rob

**Comment by shawnlaffan** [comment] 2023-08-06 10:33
I've just realised this is only a warning, not an error.  My chagrin is now well nourished.  

The perl interpreter is working as designed.

If needed the warning can be suppressed using the usual idioms, for example:

```perl
no warnings qw/locale/;
```

That does not quite explain the issue with ```en_US.UTF-8``` reported by @blues1875 but that could be due to uninstalled locales.

**Comment by sisyphus** [comment] 2023-08-06 12:01
> I've just realised this is only a warning, not an error. 

It's odd that the warning doesn't quote a line number.
UIM, that omission of the line number is a perl bug ??

> That does not quite explain the issue with <code>en_US.UTF-8</code> reported by @blues1875 but that could be due to uninstalled locales.

Yes, I think that locale is unavailable - but only with mingw-w64 builds of perl.
For me, on Windows 11, with VS2022-built perl-5.38.0, I get:
```
>perl -MPOSIX -wle "$loc = POSIX::setlocale( LC_ALL, 'en_US.UTF-8' ); print $loc;"
en_US.UTF-8
```
but with mingw-w64-built perl-5.38.0, the same command produces:
```
perl -MPOSIX -wle "$loc = POSIX::setlocale( LC_ALL, 'en_US.UTF-8' ); print $loc;"
Use of uninitialized value $loc in print at -e line 1.
```
I assume that, whenever the requested locale is unavailable, then $loc will will be undefined, but that it will otherwise be set to the requested value.

Cheers,
Rob

**Comment by macoyama** [comment] 2023-08-08 23:27
Hi.
Thank you for development.
I tested in a Windows 11 Japanese environment. This resulted in a similar message.

>perl -V | findstr uname
Locale 'Japanese_Japan.932' is unsupported, and may crash the interpreter.
    uname='Win32 strawberry-perl 5.38.0.2 # 23:06:19 Fri August 04 2023 x64'

I inform you that the same applies to the Japanese environment.

**Comment by shawnlaffan** [comment] 2023-08-08 23:58
@macoyama - thanks for reporting.  

This looks to be pretty widespread among such locales.  

@genio linked to this Perl/perl5 issue above but this comment looks to have some explanatory material related to getting values from the environment:  https://github.com/Perl/perl5/issues/20373#issuecomment-1519254293

The warning is legitimate but how often is the crash likely to be triggered?  The paucity of reports with 5.36 and earlier suggests it is quite rare?

A general question is whether there is a perl invocation on machines with these locales that does not trigger the warning?  That might help narrow things down.

**Comment by macoyama** [comment] 2023-08-09 07:35
@shawnlaffan - Thanks for the reply.
Thanks also for the link to perl/perl5#20373.

I am using DBIx::simpe to manipulate SQLite3 and have never had a crash.
I will try using it for a while.

**Comment by shawnlaffan** [comment] 2023-08-11 23:41
Line numbers have been added to the warning in https://github.com/Perl/perl5/pull/21365

I'll add add it to a 5.38 dev build when next I run one.

**Comment by hwhsu1231** [comment] 2023-08-15 03:16
I met the same problem when using Strawberry Perl version `v5.38.0`:

```cmd
C:\Users\hwhsu1231>where perl
C:\Strawberry\perl\bin\perl.exe

C:\Users\hwhsu1231>perl --version
Locale 'Chinese (Traditional)_Taiwan.950' is unsupported, and may crash the interpreter.

This is perl 5, version 38, subversion 0 (v5.38.0) built for MSWin32-x64-multi-thread

Copyright 1987-2023, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at https://www.perl.org/, the Perl Home Page.
```

**Comment by shawnlaffan** [comment] 2023-10-15 21:43
Cross-ref to report on the perl5 repo:  https://github.com/Perl/perl5/issues/21562

**Comment by genio** [comment] 2024-04-19 12:25
It's being discussed in issue #150

**Closed by genio** 2024-04-19 12:25 UTC
Labels: perl core
