### ISSUE TITLE
Strawberry Perl 32bit version

### ISSUE THREAD

**Issue by aero** [StrawberryPerl/Perl-Dist-Strawberry#96] opened 2023-04-25 01:45 UTC
Will the 32-bit version also be included in the next 5.36 release? just like previous versions of Strawberry Perl did.

There are some legacy Windows OLE/COM components that only support 32-bit versions, so that case needs a 32-bit version of Perl.
So, even Python and Ruby continue to release 32-bit versions along with their official distributions.

**Comment by AgostinoSturaro** [comment] 2023-07-17 12:57
About #94 
I have the same question, the 64-bit Win32::OLE module cannot load 32-bit dlls
https://www.perlmonks.org/?node_id=824725

For example, the InstallShield 2022 automation interface is still 32-bit
https://docs.revenera.com/installshield28helplib/helplibrary/IHelpAutomation.htm

**Comment by shawnlaffan** [comment] 2023-07-17 22:10
@AgostinoSturaro - the perlmonks node you link to is more than ten years old.  Is it still correct?  

It might be that we can release a cut-down version for 32-bit.  For example, there is no point releasing a 32 bit PDL version so that reduces the number of external libs that would need to be built.  And it is the external libs that are the main sticking point.  

I'll give this some thought but without any promises for when.

**Comment by AgostinoSturaro** [comment] 2023-07-19 08:07
@shawnlaffan Yes, it is still valid, I found that page searching for an error we got when we tried to run InstallShield automation using 64-bit Perl. Moving to 32-bit (same distro and version) solved it.

**Comment by wchristian** [comment] 2023-10-15 15:18
I think a 32 bit version may be necessary.

I just tried to install IO::AIO with the newest portable 5.38 64 bit strawberry perl and got this install error:

```
AIO.xs: In function 'req_invoke':
AIO.xs:778:30: error: incompatible types when assigning to type 'struct w32_stat' from type 'struct _stat64'
  778 |               PL_statcache = *(EIO_STRUCT_STAT *)(req->ptr2);
      |                              ^
```

**Comment by genio** [comment] 2023-10-15 17:20
Newer GCC since back then... ?

Maybe reach out to MLEHMANN to see if you can work with him on it? It's very hard to know what's going on in that particular author's dists since he doesn't use any public issue tracking system that I'm aware of.

I see there was already an issue created on RT over 2 years ago: https://rt.cpan.org/Public/Bug/Display.html?id=138060 but there's no way to tell if anything was ever done with it.

**Comment by tonycoz** [comment] 2023-10-15 21:16
> ```
> AIO.xs:778:30: error: incompatible types when assigning to type 'struct w32_stat' from type 'struct _stat64
> ```

32-bit builds won't fix this. We switched to our own stat struct in 5.34 for the stat rewrite, since the MSVCRT/UCRT stat struct uses short for st_dev and st_ino.

**Comment by AgostinoSturaro** [comment] 2023-11-25 20:25
We still need a 32-bit version to run the InstallShield automation, which is 32-bit COM stuff.
https://docs.revenera.com/installshield28helplib/helplibrary/AutomationInterface64Bit.htm#automatingbuildprocesses_355067736_1031239

**Comment by sisyphus** [comment] 2023-11-26 06:38
> We still need a 32-bit version to run the InstallShield automation, which is 32-bit COM stuff

Which of the modules from strawberry perl's vendor/lib are required to run this "InstallShield automation" ?
I'm thinking it's probably much simpler for you to build perl yourself and use the <code>cpan</code> utility to install any extra modules that are needed .... but that depends upon the answer to the question I've just asked.

**Comment by AgostinoSturaro** [comment] 2023-11-26 21:22
It's not specific to `InstallShield`, it's the `Win32::OLE` module to load COM stuff, like this
```
use Win32::OLE;
my $dev = Win32::OLE->new(“IswiAuto17.ISWiProject”);
```

Here is an example
https://www.revenera.com/blog/software-installation/getting-started-with-installshield-automation-and-perl/

The issue is that we can't use the 64-bit version of `Win32::OLE` because it can't load the 32-bit InstallShield COM stuff.
So we need the 32-bit `Win32::OLE` module.

**Comment by genio** [comment] 2023-11-26 22:03
Out of curiosity, would not Wix or the MS Visual Studio Installer Project be easier to deal with at this point than the necessity for a  32-bit Perl for InstallShield?

**Comment by sisyphus** [comment] 2023-11-26 23:57
> So we need the 32-bit Win32::OLE module

If that's all you need, then I would certainly recommend that you build and install your own perl-5.38.0 from source and then run <code>cpan -i Win32::OLE</code>
There's not a lot to it.
If you're interested, start by downloading and unpacking:
https://github.com/brechtsanders/winlibs_mingw/releases/download/13.1.0-16.0.5-11.0.0-msvcrt-r5/winlibs-i686-posix-dwarf-gcc-13.1.0-mingw-w64msvcrt-11.0.0-r5.7z
and
https://cpan.metacpan.org/authors/id/R/RJ/RJBS/perl-5.38.0.tar.gz

Put your winlibs/mingw32/bin folder at the start of your PATH
Then cd to perl-5.38.0/win32 source directory and run:
gmake CCTYPE=GCC CCHOME=path_to_winlibs/mingw32 WIN64=undef INST_TOP=path_to_install_perl_into test
When that completes, re-run the same command but replace "test" with "install".
(Copy a strawberry perl gmake.exe to your winlibs/mingw32/bin folder if gmake isn't already in your path.)

However, if you need to also use other modules that Strawberry Perl provides in vendor/lib, then things might become a little troublesome for you if any of those modules need to be built against a 3rd party C library.
The great value of Strawberry Perl is not the "Perl" - it's all of those 3rd party libraries, and the modules provided in vendor/lib that build against one or more of those libraries.
Which other vendor/libs (apart from Win32::OLE) do you need ?

**Comment by shawnlaffan** [comment] 2023-11-27 00:28
I ran the code snippet from https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/96#issuecomment-1826900610 through [pp_autolink](https://metacpan.org/pod/App::PP::Autolink) under a 32 bit portable version 5.32.  It detected the following dependent DLLs.

```
c:/perls/strawberry-perl-5.32.1.1-32bit-portable/perl/bin/libgcc_s_dw2-1.dll 
c:/perls/strawberry-perl-5.32.1.1-32bit-portable/c/bin/libssl-1_1_.dll 
c:/perls/strawberry-perl-5.32.1.1-32bit-portable/c/bin/zlib1_.dll 
c:/perls/strawberry-perl-5.32.1.1-32bit-portable/c/bin/libcrypto-1_1_.dll
```

So any 32-bit perl would also need to provide ssl, zlib and libcrypto.  

One option is to use the compiler and libs that come with SP 5.32 as that would avoid potential headaches with building using a more recent GCC.  We had to handle a few such issues with GCC-13 for SP 5.36 and 5.38.

**Comment by shawnlaffan** [comment] 2023-11-27 22:59
I went ahead and generated a 32-bit version of 5.38.1 using the gcc stack and other libs from SP 5.32.1.  The build went relatively smoothly with most CPAN failures being the same as for the 5.38 builds, and thus having the same workarounds.  

https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/dev_5381_32bit 

@AgostinoSturaro and @aero - can you please download and test for your use cases?

If it all works well enough then I'll run a new build when the Perl 5.38.1 release is stabilised (probably as 5.38.2:   https://www.nntp.perl.org/group/perl.perl5.porters/2023/11/msg267372.html ).

**Comment by aero** [comment] 2023-11-28 02:47
@shawnlaffan 
I am compiling 32bit perl 5.38 and using it myself as [@sisyphus taught](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/96#issuecomment-1826944996) me
but I also tested your https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/dev_5381_32bit and Win32::OLE for 32bit COM components works well.
(Except issue like https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/119 is still exist.)

**Comment by shawnlaffan** [comment] 2023-11-28 03:06
Thanks for confirming @aero.  

This release will not address #119 since it uses the MSVCRT runtime.  I have started building with UCRT that will hopefully do so, but it's still a work in progress.  Updates will be under #152 (see also discussion in #150).

**Comment by tonycoz** [comment] 2023-11-28 20:51
UCRT makes no difference to #119, it's a core perl issue

**Comment by shawnlaffan** [comment] 2023-11-28 21:08
> UCRT makes no difference to #119, it's a core perl issue

It seems my optimism has proven unfounded once more.  

I guess we wait for the issue to be handled in core perl.

**Comment by tonycoz** [comment] 2023-11-28 21:21
The issue is how to handle it, there's been some discussion at https://github.com/Perl/perl5/issues/21562

**Comment by gregoa** [comment] 2023-11-28 23:37
> I went ahead and generated a 32-bit version of 5.38.1 using the gcc stack and other libs from SP 5.32.1. The build went relatively smoothly with most CPAN failures being the same as for the 5.38 builds, and thus having the same workarounds.

Thank you very much!

Installed, and my old laptop is sending its first CPAN smoke test reports :)
Nothing unusual so far …

**Comment by shawnlaffan** [comment] 2023-11-30 09:04
A 32-bit version of 5.38.2 can be downloaded from https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/SP_5382_32bit

**Comment by shawnlaffan** [comment] 2023-12-06 22:19
> Still terribly buzy, but planning on trying the zip.

No rush - you did say next week.  I just flagged the issue so I remember to close it when you respond.

**Comment by AgostinoSturaro** [comment] 2023-12-09 11:58
I checked. The `Win32::OLE` works.

We also use (among others)
`Win32`, `Win32::API`, `Win32::File`, `Win32::Process`, `Win32::TieRegistry`.

During my test, I had to bypass calls to `Win32::API` and `Win32::File` calls, because those packages are not part of the build.
There are probably others, this was just what was needed for my quick test case.

It would be nice to have a full 32-bit build with all packages.
Thank you.

**Comment by shawnlaffan** [comment] 2023-12-09 21:07
```Win32::API``` and ```Win32::File``` are both part of the build.  

```
perl -v | findstr version
This is perl 5, version 38, subversion 2 (v5.38.2) built for MSWin32-x86-multi-thread-64int

perl -MWin32::File -E"say $Win32::File::VERSION"
0.07

perl -MWin32::API -E"say $Win32::API::VERSION"
0.84
```

We are unlikely to build the full set of packages for 32-bit.  However, the stack does include all the external libs from the 5.32 release so it is possible to build packages locally.

**Comment by AgostinoSturaro** [comment] 2023-12-09 23:16
That's odd. I had errors about the Dynaloader not being able to load them.
I'll take a look at my lib paths (next week), maybe it was looking for the wrong thing.

Still, I can't advocate using a test build in production, and we need to all use the same package internally, so a local build wouldn't be practical.
Please consider making an official 32-bit release.

**Comment by shawnlaffan** [comment] 2023-12-10 02:00
> Please consider making an official 32-bit release.

This is an official release.  It just does not contain as many pre-built packages as the 64 bit version.

**Comment by AgostinoSturaro** [comment] 2023-12-17 18:10
> `Win32::API` and `Win32::File` are both part of the build.
> 
> ```
> perl -v | findstr version
> This is perl 5, version 38, subversion 2 (v5.38.2) built for MSWin32-x86-multi-thread-64int
> 
> perl -MWin32::File -E"say $Win32::File::VERSION"
> 0.07
> 
> perl -MWin32::API -E"say $Win32::API::VERSION"
> 0.84
> ```
> 
> We are unlikely to build the full set of packages for 32-bit. However, the stack does include all the external libs from the 5.32 release so it is possible to build packages locally.

OK, I tested again with a simpler env and they work.
If this is an official release, please make it available in the Downloads page.
Thank you.

**Comment by shawnlaffan** [comment] 2023-12-17 22:20
> OK, I tested again with a simpler env and they work.

Thanks for confirming.  

> If this is an official release, please make it available in the Downloads page.

The release notes were updated in https://github.com/StrawberryPerl/strawberryperl.com/pull/45 but it looks like they have not been published yet.  @genio - fyi

**Comment by genio** [comment] 2023-12-17 22:35
Yeah, that table still needs to be updated manually. If one of y'all wants to throw in a PR for that, I'll gladly merge and update. I've been fairly busy with life kicking me as hard as possible lately. Apologies.

**Comment by shawnlaffan** [comment] 2023-12-18 00:12
I've added issues to update the release table and releases.json files.  See https://github.com/StrawberryPerl/strawberryperl.com/issues/47 and https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/163

I'll close this issue now as we have an open PR for the 32-bit 5.38 release notes update.

**Closed by shawnlaffan** 2023-12-18 00:12 UTC
Labels: closable, 32bit

**Comment by ANVLISTENER** [comment] 2025-01-27 12:07
@AgostinoSturaro  Can you explain why InstallShield 2024 is failing to create an object. Looking for root cause. can we get that running using perl5.38 64-bit. 

We're using the code. 

```
Set WshShell = WScript.CreateObject("WScript.Shell")
Set WshSysEnv = WshShell.Environment("Process")
strAutomationObj = WshSysEnv("InstallShieldAutomationObject")

Wscript.echo "This is our InstallShield Object" & strAutomationObj
```

This is in .vbs script. I tried seeing through the code and pondering out. looking for a brief.

**Comment by AgostinoSturaro** [comment] 2025-01-31 21:58
> [@AgostinoSturaro](https://github.com/AgostinoSturaro) Can you explain why InstallShield 2024 is failing to create an object. Looking for root cause. can we get that running using perl5.38 64-bit.
> 
> We're using the code.
> 
> ```
> Set WshShell = WScript.CreateObject("WScript.Shell")
> Set WshSysEnv = WshShell.Environment("Process")
> strAutomationObj = WshSysEnv("InstallShieldAutomationObject")
> 
> Wscript.echo "This is our InstallShield Object" & strAutomationObj
> ```
> 
> This is in .vbs script which fails. I tried seeing through the code and pondering out but couldn't get you. looking for a brief.

It won't work.
If I remember correctly, it's because 64-bit processes cannot use 32-bit COM objects, like the InstallShield one.

See my comment
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/96#issuecomment-1826900610

@shawnlaffan It would be useful to have a 32-bit Perl distro.

**Comment by shawnlaffan** [comment] 2025-01-31 23:46
> [@shawnlaffan](https://github.com/shawnlaffan) It would be useful to have a 32-bit Perl distro.

https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/SP_5382_32bit

**Comment by AgostinoSturaro** [comment] 2025-02-10 22:21
@shawnlaffan Any chance for an official release? It would make it a lot easier for me to recommend updating if it appeared in https://strawberryperl.com/releases.html

Thank you for your work.

**Comment by shawnlaffan** [comment] 2025-02-10 22:35
> [@shawnlaffan](https://github.com/shawnlaffan) Any chance for an official release? It would make it a lot easier for me to recommend updating if it appeared in https://strawberryperl.com/releases.html

Anything in the [releases list](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases) not marked as a development release is official.  

The [releases file](https://github.com/StrawberryPerl/strawberryperl.com/blob/gh-pages/releases.json) from which the website is build can also be referred to.

That said, the website does need to be updated.  @genio - are you able to trigger a rebuild?
