### ISSUE TITLE
make "invalid output sync mutex" in 5.38.0.1

### ISSUE THREAD

**Issue by mdavidsaver** [StrawberryPerl/Perl-Dist-Strawberry#148] opened 2023-10-24 19:15 UTC
The "make.exe" bundled with 5.38.0.1 appears to have an issue which causes the `--output-sync` / `-O` flag to error out when a recursive make is attempted.

```
  make -C ./configure install
  make: *** invalid output sync mutex: --.  Stop.
  make: *** [configure/RULES_DIRS:85: configure.install] Error 2
```

I have reported this [on upstream gnumake](https://savannah.gnu.org/bugs/index.php?64806).  However, I wonder if this is the result of a buggy patch.

```
$ zipinfo strawberry-perl-5.36.1.1-64bit-portable.zip |grep -i 'make\.exe'
-rwxrwxrwx  2.0 unx 10614798 b- defX 23-Jun-04 17:24 c/bin/cmake.exe
-rwxrwxrwx  2.0 unx   254990 b- defX 23-Jun-04 17:24 c/bin/gmake.exe
-rwxrwxrwx  2.0 unx   254990 b- defX 23-Jun-04 17:24 c/bin/make.exe
-rwxrwxrwx  2.0 unx   254990 b- defX 23-Jun-04 17:24 c/bin/mingw32-make.exe
```

Is there anything in the [release notes](https://strawberryperl.com/release-notes/5.38.0.1-64bit.html) to tell me where this mingw32-make build came from?

**Comment by genio** [comment] 2023-10-24 19:17
That `mingw32-make.exe` comes directly from [WinLibs](https://winlibs.com/).

https://github.com/brechtsanders/winlibs_mingw

**Comment by genio** [comment] 2023-10-24 19:22
We put copies in place here: https://github.com/StrawberryPerl/spbuild/blob/main/5.34/Dockerfile#L30-L31 to help with builds

**Comment by mdavidsaver** [comment] 2023-10-24 19:40
> That `mingw32-make.exe` comes directly from [WinLibs](https://winlibs.com/).

Ah, "winlibs" does appear in the release notes, although only in GCC output.  eg. `--prefix=/R/winlibs64_stage/inst_gcc-13.1.0/share/gcc`.  Also "Gcc version details" ends with:

```
gcc version 13.1.0 (MinGW-W64 x86_64-msvcrt-posix-seh, built by Brecht Sanders)
```

**Comment by mdavidsaver** [comment] 2023-10-28 19:52
Unfortunately, I think I have exhausted what I say about this issue.  As mentioned in https://github.com/brechtsanders/winlibs_mingw/issues/174#issuecomment-1783904159 circumstances keep me from further testing with 5.38.0.1 at present.

> We put copies in place here ...

My $0.02, it would have been better if strawberry perl had never installed `make.exe`.  However, at the moment I have a workaround in manipulating `%PATH%` to prefer the other ([ezwinports](https://bitbucket.org/xoviat/chocolatey-packages/src/master/make/4.4.1/tools/VERIFICATION.txt)) build where `-Otarget -j2` works.  This should be sufficient as long as choco and/or future strawberryperl installers don't start overwriting `C:\ProgramData\Chocolatey\bin\make.exe`.

**Comment by shawnlaffan** [comment] 2023-10-28 22:01
> However, at the moment I have a workaround in manipulating %PATH% to prefer the other ([ezwinports](https://bitbucket.org/xoviat/chocolatey-packages/src/master/make/4.4.1/tools/VERIFICATION.txt)) build where -Otarget -j2 works.

Another option is to delete the ```make.exe``` from the strawberry perl ```c/bin``` directory as a step in the workflow.  There might be other clashes, though.  

The root cause of the issue seems to be that the make executables do not support recursive calls when they have been renamed.  Calling as ```mingw32-make``` will work in this case, but not ```make``` and I suspect also not ```gmake```.  I would assume that the ```gmake``` that comes with Strawberry Perl 5.32 will have the same issues if it is renamed to ```make```.

And FWIW, the issue of clashing executables is not restricted to Strawberry Perl.  I have code in ```Alien::``` modules to strip out some of the git related paths because their MSYS2 derived utilities are not compatible with the MSYS utilities used in the [Alien::Build](https://metacpan.org/pod/Alien::Build) system.  Normally these are not in the path but under Github actions they are (or perhaps were as I have not checked for a while).

**Comment by mdavidsaver** [comment] 2023-11-05 19:31
> ... Calling as `mingw32-make` will work in this case, but not `make` ...

There may be more to it.  In a WINE environment, I get misbehavior with both executable names.  See https://github.com/brechtsanders/winlibs_mingw/issues/174#issuecomment-1793823524

**Comment by shawnlaffan** [comment] 2023-12-05 20:50
Just noting that the 5.38.2.1 and 5.36.3.1 builds still use the copied ```gmake.exe``` so this general problem remains for those distributions.  However, they do not include ```make.exe``` so the original cause of the report is now side-stepped.

**Comment by shawnlaffan** [comment] 2024-06-14 06:41
The ```mingw32-make``` (and thus ```gmake```) that are provided with the SP 5.40-RC1 build have a different size so presumably the winlibs build process has changed a few things.  Given that, does the issue still occur?

https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/dev_5.40.0_RC1_UCRT

Winlibs release: https://github.com/brechtsanders/winlibs_mingw/releases/download/13.1.0-16.0.5-11.0.0-ucrt-r5/winlibs-x86_64-posix-seh-gcc-13.1.0-mingw-w64ucrt-11.0.0-r5.zip

**Comment by shawnlaffan** [comment] 2024-08-12 02:13
I think this is closable as not a strawberry perl issue.  

The Makefile from https://github.com/brechtsanders/winlibs_mingw/issues/174#issuecomment-1793823524 produces the same output whether called using mingw32-make or gmake from the SP 5.40.0.1 release.  This is consistent with the note in https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/148#issuecomment-1793824858

The process works when ```-j1``` is used, and fails for ```-j2``` or ```-j```.  

Output from ```gmake``` is below.  


```
C:\strawberry\bugs\issue_174> gmake -j1 -Otarget
gmake echo-foo
gmake[1]: Entering directory 'C:/strawberry/bugs/issue_174'
echo echo-foo
echo-foo
gmake[1]: Leaving directory 'C:/strawberry/bugs/issue_174'
gmake echo-bar
gmake[1]: Entering directory 'C:/strawberry/bugs/issue_174'
echo echo-bar
echo-bar
gmake[1]: Leaving directory 'C:/strawberry/bugs/issue_174'
```


```
C:\strawberry\bugs\issue_174> gmake -j2 -Otarget
gmake echo-foo
gmake echo-bar
: option '--sync-mutex' requires an argument
Usage: gmake [options] [target] ...
Options:
  -b, -m                      Ignored for compatibility.
  -B, --always-make           Unconditionally make all targets.
  -C DIRECTORY, --directory=DIRECTORY
                              Change to DIRECTORY before doing anything.
  -d                          Print lots of debugging information.
: option '--sync-mutex' requires an argument
  -Usage: gmake [options] [target] ...
-debug[=FLAGS]             Print various types of debugging information.
Options:
  -e, --environment-overrides
                              Environment variables override makefiles.
  -b, -m                      Ignored for compatibility.
  -E STRING, --eval=STRING    Evaluate STRING as a makefile statement.
  -B, --always-make           Unconditionally make all targets.
  -f FILE, --file=FILE, --makefile=FILE
                              Read FILE as a makefile.
  -C DIRECTORY, --directory=DIRECTORY
                              Change to DIRECTORY before doing anything.
  -h, --help                  Print this message and exit.
  -d                          Print lots of debugging information.
  -i, --ignore-errors         Ignore errors from recipes.
  --debug[=FLAGS]             Print various types of debugging information.
  -I DIRECTORY, --include-dir=DIRECTORY
                              Search DIRECTORY for included makefiles.
  -e, --environment-overrides
                              Environment variables override makefiles.
  -j [N], --jobs[=N]          Allow N jobs at once; infinite jobs with no arg.
  -E STRING, --eval=STRING    Evaluate STRING as a makefile statement.
  --jobserver-style=STYLE     Select the style of jobserver to use.
  -f FILE, --file=FILE, --makefile=FILE
                              Read FILE as a makefile.
  -k, --keep-going            Keep going when some targets can't be made.
  -h, --help                  Print this message and exit.
  -l [N], --load-average[=N], --max-load[=N]
                              Don't start multiple jobs unless load is below N.
  -i, --ignore-errors         Igno  -L, --check-symlink-times   Use the latest mtime between symlinks and target.
re errors from recipes.
  -n, --just-print, --dry-run, --recon
                              Don't actually run any recipe; just print them.
  -I DIRECTORY, --include-dir=DIRECTORY
                              Search DIRECTORY for included makefiles.
  -o FILE, --old-file=FILE, --assume-old=FILE
                              Consider FILE to be very old and don't remake it.
  -j [N], --jobs[=N]          Allow N jobs at once; infinite jobs with no arg.
  -O[TYPE], --output-sync[=TYPE]
                              Synchronize output of parallel jobs by TYPE.
  --jobserver-style=STYLE     Select the style of jobserver to use.
  -p, --print-data-base       Print make's internal database.
  -k, --keep-going            Keep going when some targets can't be made.
  -q, --question              Run no recipe; exit status says if up to date.
  -l [N], --load-average[=N], --max-load[=N]
                              Don't start multiple jobs unless load is below N.
  -r, --no-builtin-rules      Disable the built-in implicit rules.
  -L, --check-symlink-times   Use the latest mtime between symlinks and target.
  -R, --no-builtin-variables  Disable the built-in variable settings.
  -n, --just-print, --dry-run, --recon
                              Don't actually run any recipe; just print them.
  --shuffle[={SEED|random|reverse|none}]
                              Perform shuffle of prerequisites and goals.
  -o FILE, --old-file=FILE, --assume-old=FILE
                              Consider FILE to be very old and don't remake it.
  -s, --silent, --quiet       Don't echo recipes.
  -O[TYPE], --output-sync[=TYPE]
                              Synchronize output of parallel jobs by TYPE.
  --no-silent                 Echo recipes (disable --silent mode).
  -p, --print-data-base       Print make's internal database.
  -S, --no-keep-going, --stop
                              Turns off -k.
  -q, --question              Run no recipe; exit status says if up to date.
  -t, --touch                 Touch targets instead of remaking them.
  -r, --no-buil  --trace                     Print tracing information.
tin-rules      Disable the built-in implicit rules.
  -v, --version               Print the version number of make and exit.
  -R, --no-builtin-variables  Disable the built-in variable settings.
  -w, --print-directory       Print the current directory.
  --shuffle[={SEED|random|reverse|none}]
                              Perform shuffle of prerequisites and goals.
  --no-print-directory        Turn off -w, even if it was turned on implicitly.
  -s, --silent, --quiet       Don't echo recipes.
  -W FILE, --what-if=FILE, --new-file=FILE, --assume-new=FILE
                              Consider FILE to be infinitely new.
  --no-silent                 Echo recipes (disable --silent mode).
  --warn-undefined-variables  Warn when an undefined variable is referenced.
  -S, --no-keep-going, --stop
                              Turns off -k.

This program built for x86_64-w64-mingw32
  -t, --touch                 Touch targets instead of remaking them.
Report bugs to <bug-make@gnu.org>
  --trace                     Print tracing information.
  -v, --version               Print the version number of make and exit.
  -w, --print-directory       Print the current directory.
  --no-print-directory        Turn off -w, even if it was turned gmake: *** [makefile:4: foo] Error 2
on implicitly.
gmake: *** Waiting for unfinished jobs....
  -W FILE, --what-if=FILE, --new-file=FILE, --assume-new=FILE
                              Consider FILE to be infinitely new.
  --warn-undefined-variables  Warn when an undefined variable is referenced.

This program built for x86_64-w64-mingw32
Report bugs to <bug-make@gnu.org>
gmake: *** [makefile:7: bar] Error 2
```

**Comment by shawnlaffan** [comment] 2024-08-15 08:16
Closing per previous comment.

**Closed by shawnlaffan** 2024-08-15 08:16 UTC
Labels: closable
