### ISSUE TITLE
StrawberryPerl 5.36+ treats unreadable files as if they don't exist

### ISSUE THREAD

**Issue by LordAro** [StrawberryPerl/Perl-Dist-Strawberry#149] opened 2023-10-25 15:19 UTC
If you have an unreadable file:

```
$ touch unreadable_file
$ /c/Windows/System32/icacls unreadable_file //deny Everyone:r
processed file: unreadable_file
Successfully processed 1 files; Failed processing 0 files
```

Strawberryperl 5.32 still believes the file exists, as you might expect:
```
$ ~/Downloads/strawberry-perl-5.32.1.1-64bit-portable/perl/bin/perl -We "print -e 'unreadable_file'"
1
```

However 5.36 & 5.38 do not:

```
$ ~/Downloads/strawberry-perl-5.38.0.1-64bit-portable/perl/bin/perl -We "print -e 'unreadable_file'"
Use of uninitialized value in print at -e line 1.

$ ~/Downloads/strawberry-perl-5.36.1.1-64bit-portable/perl/bin/perl -We "print -e 'unreadable_file'"
Use of uninitialized value in print at -e line 1.
```
(Using fresh downloads from strawberryperl.com)

I can't see anything in the perl 5.34 (which I'm unable to test) or 5.36 release notes that looks particularly relevant.

Any ideas what's going on?

If relevant (though I don't think so, the shell itself can read the file just fine) :
```
$ pacman -Q msys2-runtime
msys2-runtime 3.4.9-2
```

and I'm using the UCRT64 MSYS2 terminal.

**Comment by shawnlaffan** [comment] 2023-10-25 21:11
Thanks for the report.  

I can reproduce this on my machine.  

If I check the error variables then it shows permission or access is denied. 

With 5.36:
```
perl -E "say -e 'unreadable_file'; say $!  "

Permission denied

perl -MWin32::LongPath=testL -E "say (testL 'e', 'unreadable_file'); say $^E "

Access is denied
```

If I run with 5.32 then I get :
```
perl -E "say -e 'unreadable_file'; say $! "
1

perl -MWin32::LongPath=testL -E "say (testL 'e', 'unreadable_file'); say $^E "

Access is denied
```

So it looks like the Win32 API (which Win32::LongPath wraps) is consistent across versions, and Perl now matches that.  

There have been some changes to stat under Windows but I don't know if they are related.  
https://github.com/Perl/perl5/commits/blead/win32/win32.c

**Comment by tonycoz** [comment] 2023-10-26 02:39
The Windows CRT stat() behaves the same, treating the file as if it doesn't exist:
```
C:\Users\Tony\dev\perl\git>type dostat.c
#include <stdio.h>
#include <sys/stat.h>
#include <string.h>

int main(int argc, const char **argv) {
  if (argc < 2) {
    fprintf(stderr, "No filenames\n");
    return 1;
  }

  for (const char **arg = argv+1; *arg; ++arg) {
    struct stat st;

    if (stat(*arg, &st) >= 0) {
      printf("stat %s success\n", *arg);
    }
    else {
      fprintf(stderr, "stat '%s' failed: %s\n", *arg, strerror(errno));
      return -1;
    }
  }
  return 0;
}

C:\Users\Tony\dev\perl\git>cl /W4 dostat.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.35.32217.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

dostat.c
dostat.c(18): warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
Microsoft (R) Incremental Linker Version 14.35.32217.1
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:dostat.exe
dostat.obj

C:\Users\Tony\dev\perl\git>dir test.txt unreadable_file
 Volume in drive C has no label.
 Volume Serial Number is 2824-036D

 Directory of C:\Users\Tony\dev\perl\git

02/07/2023  10:51 AM                 3 test.txt

 Directory of C:\Users\Tony\dev\perl\git

26/10/2023  01:26 PM                 4 unreadable_file
               2 File(s)              7 bytes
               0 Dir(s)  158,618,583,040 bytes free

C:\Users\Tony\dev\perl\git>dostat test.txt unreadable_file
stat test.txt success
stat 'unreadable_file' failed: No such file or directory
```
The stat() re-work doesn't use the CRT stat, but it was originally modelled on it.

I don't see a simple fix.

**Comment by LordAro** [comment] 2023-10-26 10:56
So is this worth raising upstream do you think? I feel like `-e` shouldn't be relying on `stat()` to determine existence if it just returns an error regardless...

**Comment by shawnlaffan** [comment] 2023-10-26 21:01
> So is this worth raising upstream do you think? I feel like `-e` shouldn't be relying on `stat()` to determine existence if it just returns an error regardless...

@LordAro - it's probably worth raising upstream so it is logged at that level given it would seem to affect more than just Strawberry Perl.  @tonycoz is a core dev so the relevant people are aware of it already.

**Comment by tonycoz** [comment] 2023-10-26 21:57
> I feel like `-e` shouldn't be relying on `stat()`

Except for `-T`, `-B` and `-t` all of the `-X` ops are wrappers around stat() or lstat().

Older versions of the CRT, and hence perl,[ used the directory search functions](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/stat-functions?view=msvc-170#remarks) to fetch file information, but that doesn't let you distinguish symbolic links from other reparse points.

I'll open a ticket for perl.

**Comment by tonycoz** [comment] 2023-10-26 22:16
https://github.com/Perl/perl5/issues/21598

**Comment by shawnlaffan** [comment] 2023-12-05 20:47
This issue has been reported upstream.  Given it is not Strawberry Perl specific I'll close this issue.  

Thanks @LordAro for reporting.

**Closed by shawnlaffan** 2023-12-05 20:47 UTC
Labels: perl core
