### ISSUE TITLE
Task::Kensho install failures.

### ISSUE THREAD

**Issue by genio** [StrawberryPerl/Perl-Dist-Strawberry#103] opened 2023-05-28 19:02 UTC
One of the easiest way to test things is to look at any failures [Task::Kensho](https://metacpan.org/pod/Task::Kensho) presents.

Using https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/tag/dev_5.36.1_20230528_gcc13 results in the following install failures:

```
lib::relative
Specio::Library::Path::Tiny
Code::TidyAll
Test::MockObject
Test::WWW::Mechanize
Time::ParseDate
Module::CPANfile
App::FatPacker
File::Next
File::NFSLock
CPAN::Checksums
```

**Comment by genio** [comment] 2023-05-28 19:43
```
cpanm -v lib::relative
cpanm (App::cpanminus) 1.7046 on perl 5.036001 built for MSWin32-x64-multi-thread
Work directory is C:\Users\CWHITE~2\DOWNLO~1\STRAWB~1.1-6\data/.cpanm/work/1685302965.4352
You have make C:\Users\cwhitener\Downloads\strawberry-perl-5.36.1.1-64bit-portable\c\bin\gmake.exe
You have LWP 6.70
Falling back to Archive::Tar 3.02
Searching lib::relative () on cpanmetadb ...
--> Working on lib::relative
Fetching http://www.cpan.org/authors/id/D/DB/DBOOK/lib-relative-1.001.tar.gz ... OK
Unpacking lib-relative-1.001.tar.gz
Entering lib-relative-1.001
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.70)
Running Makefile.PL
Configuring lib-relative-1.001 ... Checking if your kit is complete...
Looks good
Generating a gmake-style Makefile
Writing Makefile for lib::relative
Writing MYMETA.yml and MYMETA.json
OK
Checking dependencies from MYMETA.json ...
Checking if you have lib 0 ... Yes (0.65)
Checking if you have File::Spec 0 ... Yes (3.84)
Checking if you have Test::More 0.88 ... Yes (1.302195)
Checking if you have Cwd 0 ... Yes (3.84)
Checking if you have File::Basename 0 ... Yes (2.85)
Checking if you have File::Temp 0.19 ... Yes (0.2311)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.70)
Building and testing lib-relative-1.001 ... cp lib/lib/relative.pm blib\lib\lib\relative.pm
"C:\Users\cwhitener\Downloads\strawberry-perl-5.36.1.1-64bit-portable\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t/*.t
t/00-report-prereqs.t .. #
# Versions for all modules listed in MYMETA.json (including optional ones):
#
# === Configure Requires ===
#
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 7.70
#
# === Build Requires ===
#
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 7.70
#
# === Test Requires ===
#
#     Module              Want     Have
#     ------------------- ---- --------
#     ExtUtils::MakeMaker  any     7.70
#     File::Spec           any     3.84
#     File::Temp          0.19   0.2311
#     Test::More          0.88 1.302195
#
# === Test Recommends ===
#
#     Module         Want     Have
#     ---------- -------- --------
#     CPAN::Meta 2.120900 2.150010
#
# === Runtime Requires ===
#
#     Module         Want Have
#     -------------- ---- ----
#     Cwd             any 3.84
#     File::Basename  any 2.85
#     File::Spec      any 3.84
#     lib             any 0.65
#
t/00-report-prereqs.t .. ok
t/lib_relative.t ....... 1/? symlink failed: Operation not permitted at t/lib_relative.t line 48.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 1 just after 6.
t/lib_relative.t ....... Dubious, test returned 1 (wstat 256, 0x100)
All 6 subtests passed

Test Summary Report
-------------------
t/lib_relative.t     (Wstat: 256 (exited 1) Tests: 6 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=2, Tests=7,  1 wallclock secs ( 0.05 usr +  0.00 sys =  0.05 CPU)
Result: FAIL
Failed 1/2 test programs. 0/7 subtests failed.
gmake: *** [makefile:866: test_dynamic] Error 1
FAIL
! Installing lib::relative failed. See C:\Users\CWHITE~2\DOWNLO~1\STRAWB~1.1-6\data\.cpanm\work\1685302965.4352\build.log for details. Retry with --force to force install it.
```

**Comment by shawnlaffan** [comment] 2023-05-28 22:46
The current Strawberry 5.36.1 builds disable symlinks due to test failures of other modules.  
https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/da78325f3fdaa309589ae159d89776f8894ab29d/share/64bit-5.36.1.1.pp#L78

It would seem lib::relative needs to modify its skip checks in that test, perhaps adapting the code in Path::Tiny
https://github.com/dagolden/Path-Tiny/blob/7a84e3c6952e8d27e3963c92e6087aac36534451/t/lib/TestUtils.pm#L26-L41

The solution/workaround for now is to install it as part of the build process, skipping that test file.

**Comment by shawnlaffan** [comment] 2023-05-28 22:53
See also #67 for the list of known symlink issues in the build, some of which only manifest on the docker instance.

**Comment by shawnlaffan** [comment] 2023-05-28 23:58
MCE is also failing.  ```t/02_do_callback_args.t``` appears to be hanging.

**Comment by shawnlaffan** [comment] 2023-05-29 00:04
```Specio::Library::Path::Tiny``` is the same basic failure as ```lib::relative```.  The check for symlink capacity is not functioning correctly.

**Comment by shawnlaffan** [comment] 2023-05-29 00:09
I think I'll re-enable the symlinks in the builds and update the test skips as needed.  Most of the issues only manifest under docker.

**Comment by shawnlaffan** [comment] 2023-05-29 01:53
So I force installed ```lib::relative``` and ```Specio::Library::Path::Tiny``` and checked the others in the list.  

- [ ] lib::relative
  Force installed
- [ ] Specio::Library::Path::Tiny
  Force installed
- [ ] Code::TidyAll
  Passes
- [ ] Test::MockObject
  This is a known issue and affects older versions of Strawberry Perl.  https://github.com/chromatic/Test-MockObject/issues/23
- [ ] Test::WWW::Mechanize
  Looks like hard coded text expectations - should check for perl version , not just windows
- [ ] Time::ParseDate
  Not sure what's going on here.  
- [ ] Module::CPANfile
  Something is going wrong with its parsing.  
- [ ] App::FatPacker
  Fails
- [ ] File::Next
  Symlink issues
- [ ] File::NFSLock
  Several other tests are skipped on Win32.
- [ ] CPAN::Checksums
  These look like directory separator differences, probably caused by the same change that necessitated File::Find::Rule to be updated.  The module tests need to be updated.

**Comment by shawnlaffan** [comment] 2023-05-29 02:17
```Net::Server``` raises issues with SSLeay (see below).  These are not raised for SP5.32.  They might not be an issue, though.  

It then hangs on ```t/server_PreFork``` test 5.  However, SP5.32 hangs on test 2 of the same file so this would not seem to be a new issue in general.


```
# Unable to load module for proto "Net::Server::Proto::SSLEAY": Could not access Fcntl constant while loading Net::Server::Proto::SSLEAY: Your vendor has not defined Fcntl macro F_GETFL, used at C:\ST5EA9~1\data\.cpanm\work\1685326113.35108\Net-Server-2.014\blib\lib/Net/Server/Proto/SSLEAY.pm line 33
BEGIN failed--compilation aborted at C:\ST5EA9~1\data\.cpanm\work\1685326113.35108\Net-Server-2.014\blib\lib/Net/Server/Proto/SSLEAY.pm line 34.
Compilation failed in require at C:\ST5EA9~1\data\.cpanm\work\1685326113.35108\Net-Server-2.014\blib\lib/Net/Server/Proto.pm line 195.
 at line 317
# Failed at line 317
not ok 35 - run ( proto => 'ssleay' )  ==>  [ '' ]
#   failed at t\Port_Configuration.t line 72
#        got: {
  bind => undef
}
#   expected: {
  bind => [{
  host => '*',
  ipv => 4,
  port => 20203,
  proto => 'ssleay'
}],
  sock => [{
  NS_host => '*',
  NS_ipv => 4,
  NS_listen => 2147483647,
  NS_port => 20203,
  NS_proto => 'SSLEAY',
  SSL_cert_file => 'somecert'
}]
}
Failed 17/51 subtests
t\SSLEAY_test.t ...........
1..4
ok 1 - Can fork on this platform
ok 2 - Got needed ports (20200 20201)
ok 3 - Pipe works
# Cannot load SSLEAY library on this platform: Could not access Fcntl constant while loading Net::Server::Proto::SSLEAY: Your vendor has not defined Fcntl macro F_GETFL, used at C:\ST5EA9~1\data\.cpanm\work\1685326113.35108\Net-Server-2.014\blib\lib/Net/Server/Proto/SSLEAY.pm line 33
BEGIN failed--compilation aborted at C:\ST5EA9~1\data\.cpanm\work\1685326113.35108\Net-Server-2.014\blib\lib/Net/Server/Proto/SSLEAY.pm line 34.
Compilation failed in require at t\SSLEAY_test.t line 15.
ok 4 # skip Skipping tests on this platform
ok
```

**Comment by Grinnz** [comment] 2023-05-29 03:03
> The current Strawberry 5.36.1 builds disable symlinks due to test failures of other modules.
> 
> https://github.com/StrawberryPerl/Perl-Dist-Strawberry/blob/da78325f3fdaa309589ae159d89776f8894ab29d/share/64bit-5.36.1.1.pp#L78
> 
> It would seem lib::relative needs to modify its skip checks in that test, perhaps adapting the code in Path::Tiny https://github.com/dagolden/Path-Tiny/blob/7a84e3c6952e8d27e3963c92e6087aac36534451/t/lib/TestUtils.pm#L26-L41
> 
> The solution/workaround for now is to install it as part of the build process, skipping that test file.

I'm happy to modify the tests if that would help. Would you mind opening an issue at https://github.com/Grinnz/lib-relative/issues

**Comment by shawnlaffan** [comment] 2023-05-29 03:17
> I'm happy to modify the tests if that would help. Would you mind opening an issue at https://github.com/Grinnz/lib-relative/issues

Thanks @book.  I've opened an issue.

**Comment by shawnlaffan** [comment] 2023-05-30 03:25
The ```File::NFSLock``` and ```MCE``` fails above look like they could be related to the same underlying cause behind the vmem changes.  Similar for [```Tk```](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/98) (after the symbol clash is fixed), [```PDL::Graphics::PLplot```](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/26#issuecomment-1565985781) and [```OpenGL```](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/102).

If so then maybe more alignment checks are needed, possibly in perl and possibly in the modules?

@sisyphus - are you able to replicate the MCE and File::NFSLock failures on your builds of 5.36 and 5.37?

**Comment by marioroy** [comment] 2023-05-30 18:35
Re: Strawberry Perl 5.36.1.1 64-bit portable edition

Perl workers are terminating unexpectedly due to receiving SEGV signal for some reason. Ditto, running use_threads => 1 (default for $^O eq 'Win32') or use_threads => 0.

Inside `MCE.pm`, temporarily replacing `MCE::Mutex->new( impl => 'Channel')` with `MCE::Mutex->new( impl => 'Flock' )` resolves `02_do_callback_args.t`, but not the one after that `02_do_callback_result.t`.

I reverted the temporary change in `MCE.pm`. Next, I commented out `MCE::Util::_sock_ready(...)` in lock method inside `MCE/Mutex/Channel.pm`. That too resolves `02_do_callback_args.t`, but again not the one after that `02_do_callback_result.t`.

The _sock_ready routine is needed on Windows. I left it commented out and added `sleep 1`. The `02_do_callback_args.t` and `02_do_callback_result.t` testing pass to completion.

The `_sock_ready` routine, inside `MCE/Util.pm`, is failing running Perl 5.36.1.1 64-bit portable edition.

https://metacpan.org/dist/MCE/source/lib/MCE/Util.pm#L284

**Comment by marioroy** [comment] 2023-05-30 18:52
The `ioctl` call is the root cause for MCE failing running Perl 5.36.1.1 64-bit portable edition.

```perl
my $val_bytes =  "\x00\x00\x00\x00";
my $ptr_bytes = unpack('I', pack('P', $val_bytes));
ioctl($socket, 0x4004667f, $ptr_bytes);
```

MCE will not work on the Windows platform `$^O eq 'MSWin32'` without `_sock_ready` or the ability to check if the socket is ready.

**Comment by marioroy** [comment] 2023-05-30 20:04
The following resolves ioctl seg-faulting. Some tests are still failing. Looking deeper.
```perl
my $val_bytes = pack('L', 0);
ioctl($socket, 0x4004667f, $val_bytes);
```

**Comment by marioroy** [comment] 2023-05-30 20:18
The following resolves ioctl seg-faulting.
```perl
my $val_bytes = pack('L', 0);
ioctl($socket, 0x4004667f, $val_bytes);  # FIONREAD
return '' if unpack('L', $val_bytes);
```
Some tests are still failing. Looking deeper.

**Comment by marioroy** [comment] 2023-05-30 20:21
The `ioctl` call (inside MCE::Util) is the root cause for MCE failing or seg-faulting, running Perl 5.36.1.1 64-bit portable edition.

https://metacpan.org/dist/MCE/source/lib/MCE/Util.pm#L284

```perl
my $val_bytes = "\x00\x00\x00\x00";
my $ptr_bytes = unpack('I', pack('P', $val_bytes));
ioctl($socket, 0x4004667f, $ptr_bytes);
```

MCE will not work on the Windows platform `$^O eq 'MSWin32'` without `_sock_ready` or the ability to check if the socket is ready. The following resolves ioctl seg-faulting.

```perl
my $val_bytes = pack('L', 0);
ioctl($socket, 0x4004667f, $val_bytes);  # FIONREAD
return '' if unpack('L', $val_bytes);
```
Some tests are still failing. Looking deeper.

**Comment by marioroy** [comment] 2023-05-30 20:34
All MCE tests pass and zero failures. However, I do not understand the non-zero exit status: 5.
```text
Test Summary Report
-------------------
t\04_channel_simple.t        (Wstat: 1280 (exited 5) Tests: 24 Failed: 0)
  Non-zero exit status: 5
  Parse errors: No plan found in TAP output
t\04_channel_simplefast.t    (Wstat: 1280 (exited 5) Tests: 19 Failed: 0)
  Non-zero exit status: 5
  Parse errors: No plan found in TAP output
t\04_channel_threads.t       (Wstat: 1280 (exited 5) Tests: 24 Failed: 0)
  Non-zero exit status: 5
  Parse errors: No plan found in TAP output
t\04_channel_threads_mp.t    (Wstat: 1280 (exited 5) Tests: 24 Failed: 0)
  Non-zero exit status: 5
  Parse errors: No plan found in TAP output
t\04_channel_threadsfast.t   (Wstat: 1280 (exited 5) Tests: 19 Failed: 0)
  Non-zero exit status: 5
  Parse errors: No plan found in TAP output
t\04_channel_threadsfast_mp.t (Wstat: 1280 (exited 5) Tests: 19 Failed: 0)
  Non-zero exit status: 5
  Parse errors: No plan found in TAP output
t\05_mce_child.t             (Wstat: 1280 (exited 5) Tests: 3 Failed: 0)
  Non-zero exit status: 5
  Parse errors: No plan found in TAP output
t\05_mce_child_max_workers.t (Wstat: 1280 (exited 5) Tests: 4 Failed: 0)
  Non-zero exit status: 5
  Parse errors: No plan found in TAP output
Files=39, Tests=458, 25 wallclock secs ( 0.14 usr +  0.03 sys =  0.17 CPU)
Result: FAIL
```

**Comment by marioroy** [comment] 2023-05-30 21:12
It seems that I cannot override the WARN handler running Perl 5.36.1.1 64-bit portable edition. The tests pass. However, the test script exits with a non-zero status (snippet extracted from t/04_channel_simple.t).

```perl
# end
{
   $chnl->enqueue("item $_") for 1 .. 2;
   $chnl->end;

   for my $method (qw/ send enqueue /) {
      local $SIG{__WARN__} = sub {
         is $_[0],
         "WARNING: ($method) called on a channel that has been 'end'ed\n",
         "channel ended, $method";
      };
   }

   is $chnl->dequeue_nb, 'item 1', 'channel ended, dequeue_nb item 1';
   is $chnl->dequeue_nb, 'item 2', 'channel ended, dequeue_nb item 2';
}
```

**Comment by marioroy** [comment] 2023-05-30 22:23
The previous diagnose is incorrect. It turned out to be the _nonblocking routine in MCE::Util. I changed it locally.

From this:
```perl
      # MSWin32 FIONBIO - from winsock2.h macro
      my $nonblocking = $_[1] ? "\x00\x00\x00\x01" : "\x00\x00\x00\x00";
      ioctl($_[0], 0x8004667e, unpack('I', pack('P', $nonblocking)));
```

To this:
```perl
      # MSWin32 FIONBIO - from winsock2.h macro
      my $nonblocking = $_[1] ? pack('L', 1) : pack('L', 0);
      ioctl($_[0], 0x8004667e,  $nonblocking);
```

All MCE tests are passing and exiting 0 status. I will release an `MCE` update after evaluating `MCE::Shared`. That too needs updating due to all MCE::Shared tests exiting non-zero status.

**Comment by marioroy** [comment] 2023-05-30 22:38
I am delighted to report the next MCE 1.885 and MCE::Shared 1.881 updates pass running Perl 5.36.1.1 64-bit portable edition.

**Comment by shawnlaffan** [comment] 2023-05-30 22:44
Thanks @marioroy - much appreciated.  

If you can provide a general description of the root cause then that will likely help when reporting issues with other modules.  

@sisyphus - thanks for the diagnoses.  I'll flag File::NFSLock as a non-blocker.

**Comment by marioroy** [comment] 2023-05-31 02:19
MCE 1.885 and MCE::Shared 1.881 have been released :)

> If you can provide a general description of the root cause then that will likely help when reporting issues with other modules.

The root cause in the case of MCE is `ioctl` not reliable using a pointer to an unsigned integer. For example, `ioctl($socket, FIONREAD, $ptr_bytes)`. Passing the packed value `ioctl($socket, FIONREAD, $val_bytes)` resolved the issue in MCE::Util (_sock_ready, _nonblocking) and MCE::Shared::Server (server loop). I also changed the pack template from `I` (unsigned integer) to `L` (unsigned long).

**Comment by shawnlaffan** [comment] 2023-05-31 02:31
Thanks again @marioroy

MCE and MCE::Shared now pass all tests with the current dev version of SP5.36.1.

**Comment by marioroy** [comment] 2023-05-31 03:50
@shawnlaffan. I did a couple of changes and thought to track down which is it that resolved the issue. Item 1 was done first followed by item 2.

Earlier testing:

1. Changing the pack template from `I` (unsigned integer) to `L` (unsigned long) did not resolve the issue.
2. So, I next tried passing a packed value versus a pointer. That resolved the issue. Unfortunately, I did not revert item 1 at the time. I'm leaving MCE 1.885 and MCE::Shared 1.881 as is, using (unsigned long).

Summary:

1. `unsigned integer` and `unsigned long` work in the case of MCE's use of ioctl.
2. Passing a pointer to ioctl was the actual reason why failing running Perl 5.36.1.

**Comment by sisyphus** [comment] 2023-05-31 05:59
> Changing the pack template from <code>I</code> (unsigned integer) to <code>L</code> (unsigned long) did not resolve the issue

Both 'int' and 'long' are always 32 bits on both Win32 && Win64 - so I think no change is to be expected.

Interestingly, the <code>pack</code> documentation says:
```
....
                l  A signed long (32-bit) value.
                L  An unsigned long value.
....
                i  A signed integer value.
                I  An unsigned integer value.
                     (This 'integer' is _at_least_ 32 bits wide.  Its exact
                      size depends on what a local C compiler calls 'int'.)
```
If that is to believed, and <code>L</code> (like its lower case <code>l</code>) is also 32-bit, then it looks to me that changing from <code>I</code> to <code>L</code> is going to make no difference on <b>all</b> operating systems - at least on the various systems that I know of.

Do I misunderstand something ?

In any case, execellent work @marioroy !!

Cheers,
Rob

**Comment by marioroy** [comment] 2023-05-31 07:45
> then it looks to me that changing from I to L is going to make no difference on all operating systems

I apologize for the confusion. Initially, I changed from I to L and not yet item 2 during earlier testing. Item 2 (passing a pointer to ioctl) is the sole reason not working running Strawberry Perl 5.36.1.1.

```perl
# not okay
my $val_bytes = pack('I', 0);
my $ptr_bytes = unpack('I', pack('P', $val_bytes));
ioctl($socket, 0x4004667f, $ptr_bytes);  # MSWin32 FIONREAD

# okay, L works too
my $val_bytes = pack('I', 0);
ioctl($socket, 0x4004667f, $val_bytes);  # MSWin32 FIONREAD
```

**Comment by sisyphus** [comment] 2023-06-19 06:49
> lib::relative, Specio::Library::Path::Tiny and File::Next all install cleanly when using Perl 5.38.0 RC1

@shawnlaffan, Is it important that they pass for me, too ? ... or is the fact that they build ok for you in your development environment all that really matters ?

File::Next does not install cleanly for me on Windows 11 with SP-5.38.0.1-RC1:
<code>
t/follow.t ........ # t/follow.t is working with temp directory \l9Twe7lj5w
Unable to create symlink \l9Twe7lj5w/dir: Operation not permitted at t/follow.t line 57.
\# Looks like your test exited with 1 before it could output anything.
t/follow.t ........ Dubious, test returned 1 (wstat 256, 0x100)
</code>

lib::relative also fails in a similar way:
<code>
t/lib_relative.t ....... 1/? symlink failed: Operation not permitted at t/lib_relative.t line 48.
\# Tests were run but no plan was declared and done_testing() was not seen.
\# Looks like your test exited with 1 just after 6.
t/lib_relative.t ....... Dubious, test returned 1 (wstat 256, 0x100)
</code>

as, too, does Specio::Library::Path::Tiny :
<code>
t/basic.t .............. Operation not permitted at t/basic.t line 98.
t/basic.t .............. Dubious, test returned 1 (wstat 256, 0x100)
</code>

I guess there might be things I could do to my build environment that would allow those tests to pass but, ideally, I think those tests scripts should detect the incapacity in my environment, and skip those failing tests.

Cheers,
Rob

**Comment by shawnlaffan** [comment] 2023-06-19 06:56
> @shawnlaffan, Is it important that they pass for me, too ? ... or is the fact that they build ok for you in your development environment all that really matters ?

Thanks for checking.  

The 5.38 checks I ran were on the build system (on a docker instance).  I'll check with a downloaded version on a local drive but would not be surprised if the failures arose again.  

If that's the case then the tests still need updating/skipping.

**Comment by shawnlaffan** [comment] 2023-10-13 02:24
The items in the list of issues in https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/103#issuecomment-1566377968 are now either resolved, skipped or not a Strawberry Perl problem.  

I'll close this issue now.  If new problems or solutions are identified then they can be raised as new issues.

**Closed by shawnlaffan** 2023-10-13 02:24 UTC
