### ISSUE TITLE
v5.40.0: The results of Win32::GetOSName on Windows 11 are displayed as if it were Windows 10

### ISSUE THREAD

**Issue by twata1** [StrawberryPerl/Perl-Dist-Strawberry#207] opened 2024-08-16 20:50 UTC
Hello,

I have run `perl -MWin32 -e "print Win32::GetOSName"` on a Windows 11 PC.
The results are displayed as if it were Windows 10.
See below.

```
----------------------------------------------
 Welcome to Strawberry Perl Portable Edition!
 * URL - https://www.strawberryperl.com/ 
 * See README.TXT for more info
---------------------------------------------- 
Perl executable: E:\strawberry-perl-5.40.0.1-64bit-portable\perl\bin\perl.exe
Perl version   : v5.40.0 / MSWin32-x64-multi-thread

E:\strawberry-perl-5.40.0.1-64bit-portable>perl -MWin32 -e "print Win32::GetOSName"
Win10Build 22631 (64-bit)

E:\strawberry-perl-5.40.0.1-64bit-portable>powershell -c "Get-ComputerInfo | Select OsName"

OsName
------
Microsoft Windows 11 Pro



E:\strawberry-perl-5.40.0.1-64bit-portable>
```

Thank you,

**Comment by shawnlaffan** [comment] 2024-08-16 23:04
I get the same on my Win11 laptop, except the build is 22621.  However, looking at more of the ```Get-ComputerInfo``` details indicates this is working correctly.

```
WindowsProductName                                      : Windows 10 Enterprise
OsName                                                  : Microsoft Windows 11 Enterprise
OsVersion                                               : 10.0.22621
```

**Comment by twata1** [comment] 2024-08-16 23:55
@shawnlaffan 
Thank you for reply.

I thought that if pull requests like https://github.com/perl-libwin32/win32/pull/40 were applied on the Win32 module side, the results would be different.
I would wait for the Win32 module maintainer to incorporate such a pull request.

Thank you,

**Comment by shawnlaffan** [comment] 2024-08-17 00:24
We do patch some CPAN modules but more commonly in cases where they otherwise do not build due to changes in Perl.  

In this case the issue is best handled upstream by the module maintainer.  

I'll close this issue now but please comment if there are reasons for it to remain open.

**Closed by shawnlaffan** 2024-08-17 00:24 UTC
Labels: upstream module
