### ISSUE TITLE
Commands separated with && are not run when called with system() on Windows

### ISSUE THREAD

**Issue by thombet** [StrawberryPerl/Perl-Dist-Strawberry#24] opened 2021-04-06 14:14 UTC
Hello,

I would like to report a bug in Strawberry Perl: when a command containing `&&` is executed with `system()` on Windows, the command after the `&&` is not executed.

The problem can be reproduced with the following code:
<details><summary>code</summary>
<p>

```perl
my $cmd="python --version && python -h";
print("Command => $cmd\n");
system($cmd);
```

</p>
</details>

When executing this code with Strawberry Perl, only the version of python is printed (from `python --version`), but the usage is not printed (from `python -h`):
<details><summary>Current output</summary>
<p>

```
Command => python --version && python -h
Python 3.9.2
```

</p>
</details>

Whereas I think both `python --version` and `python -h` should be printed:
<details><summary>Expected output</summary>
<p>

```
Command => python --version && python -h
Python 3.9.2
usage: C:\python\python-3.9.2\python.exe [option] ... [-c cmd | -m mod | file | -] [arg] ...
Options and arguments (and corresponding environment variables):
[...]
```

</p>
</details>

The problem was seen on Windows 10 and Strawberry Perl 5.32.1.1 portable 64 bit:
<details><summary>perl 5.32.1.1 version details</summary>
<p>

```
perl --version

This is perl 5, version 32, subversion 1 (v5.32.1) built for MSWin32-x64-multi-thread
```

</p>
</details>

But this code works correctly (i.e. both `python --version` and `python -h` are printed) in the following conditions:
* in Git Bash on Windows 10 with perl 5.30.2:
<details><summary>perl 5.30.2 version details</summary>
<p>

```
perl --version
This is perl 5, version 30, subversion 2 (v5.30.2) built for x86_64-msys-thread-multi
```

</p>
</details>

* Debian with perl 5.28.1:
<details><summary>perl 5.28.1 version details</summary>
<p>

```
perl --version
This is perl 5, version 28, subversion 1 (v5.28.1) built for x86_64-linux-gnu-thread-multi
```

</p>
</details>

What is even stranger is that it works with some basic commands. For instance if the command run is `echo first test && echo test` then both commands are correctly executed:
```
Command => echo first test && echo test
first test
test
```

Could you please confirm the bug on your side?
Thanks in advance.

**Comment by alphacabbage1** [comment] 2021-04-06 18:39
I don't know much about system() and the dividing line between commands/parameters, shell substitution/escapes, etc but _suspect_ it wont be considered a bug.  This works under WIn10...

```
my $cmd=qq("python --version && python -h && perl -v");
print("Command => $cmd\n");
system($cmd);
```



```

Command => "python --version && python -h && perl -v"
Python 3.9.4
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
[...]
This is perl 5, version 32, subversion 1 (v5.32.1) built for MSWin32-x64-multi-thread
[...]
```

**Comment by thombet** [comment] 2021-04-06 20:54
Thanks for the fast reply.

Maybe it is not a bug in perl itself but I think there is a problem somewhere: it is quite disturbing that this code runs differently on Strawberry Perl compared to other perl versions (including on the same OS with Git Bash). Especially since Strawberry Perl `is designed to be as close as possible to perl environment on UNIX systems.`.
What do you think?

**Comment by shawnlaffan** [comment] 2023-02-16 11:24
This is likely a generic issue with how ```system``` calls are run under windows.  

The Strawberry perl environment is close to unix in how it is built and some of the tools provided, but still runs as a Windows program.  Any system call will use the windows shell, not a unix shell (although I think some system calls sidestep the shell).

Git bash is a cut-down version of MSYS (or a similar environment) so is essentially a unix environment.  That would be why it behaves as expected.  

What happens when you run the script using a non-Strawberry perl on native Windows?

**Comment by thombet** [comment] 2023-03-02 14:17
Thanks for reviving this topic @shawnlaffan 😃 

I tried to run the following code

```perl
my $cmd="python --version && python -h";
print("Command => $cmd\n");
system($cmd);
```

with ActiveState perl 5.36.0 on Windows 10 and here is the output:

```
Command => python --version && python -h
```

➡️ None of the python commands are run so the behaviour is wrong (or at least not expected) and different than Strawberry perl (I was not able to try the same code with a recent version of Strawberry perl because the website https://strawberryperl.com/ is currently down...).

**Comment by shawnlaffan** [comment] 2023-03-02 20:35
Thanks for trying with AS Perl.  This would seem to be a more generic issue than Strawberry Perl.  

It's probably worth following up with sites like [perlmonks](https://www.perlmonks.org/), [stackoverflow](https://stackoverflow.com/questions/tagged/perl) or [reddit](https://www.reddit.com/r/perl/). 

And out of curiosity, do you get the same issue when running under powershell?  (This will need manual path updates as we don't yet have a powershell version of portableshell.bat - see #52).

Once I get a strawberry 5.36 build working I'll also have a go with that.

**Comment by shawnlaffan** [comment] 2023-05-28 05:28
Testing under 5.36 shows the same behaviour.  

Given the issue is more generic than Strawberry Perl it is best raised on a more general channel, and perhaps as a perl issue.  

I'll close this issue in a few days unless there are good reasons to keep it open.

**Comment by shawnlaffan** [comment] 2023-07-25 04:32
[Win32::ShellQuote](https://metacpan.org/pod/Win32::ShellQuote) looks to be a solution here, or at least a workaround. 

I did not manage to get the list form to work but the scalar form with ```quote_native``` seems to do the trick.

```
use Win32::ShellQuote qw(:all);

my $cmd = q /perl -v && perl -v/;
say quote_native($cmd);
system quote_native($cmd);
```

Produces:

```
"perl -v && perl -v"

This is perl 5, version 38, subversion 0 (v5.38.0) built for MSWin32-x64-multi-thread

Copyright 1987-2023, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at https://www.perl.org/, the Perl Home Page.


This is perl 5, version 38, subversion 0 (v5.38.0) built for MSWin32-x64-multi-thread

Copyright 1987-2023, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at https://www.perl.org/, the Perl Home Page.

```


I'll close this issue now but it can be re-opened if there is a demonstrated need.

**Closed by shawnlaffan** 2023-07-25 04:32 UTC
