### ISSUE TITLE
Bit::Vector errors on install

### ISSUE THREAD

**Issue by weekbacker** [StrawberryPerl/Perl-Dist-Strawberry#30] opened 2021-09-16 22:04 UTC
cpan Bit:Vector errors out at the following command:

t/30__overloaded.t .. ok
t/40___auxiliary.t .. ok
t/50_freeze_thaw.t .. ok
t/51_file_nstore.t .. can't create t/51_file_nstore.tmp: Permission denied at t/51_file_nstore.t line 73.
t/51_file_nstore.t .. Dubious, test returned 13 (wstat 3328, 0xd00)
Failed 6529/7083 subtests

Test Summary Report
-------------------
t/51_file_nstore.t (Wstat: 3328 Tests: 554 Failed: 0)
  Non-zero exit status: 13
  Parse errors: Bad plan.  You planned 7083 tests but ran 554.
Files=23, Tests=85050,  6 wallclock secs ( 3.61 usr +  0.09 sys =  3.70 CPU)
Result: FAIL
Failed 1/23 test programs. 0/85050 subtests failed.
gmake: *** [Makefile:1033: test_dynamic] Error 13
  STBEY/Bit-Vector-7.4.tar.gz
  C:\perlsb\c\bin\gmake.exe test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports STBEY/Bit-Vector-7.4.tar.gz
Stopping: 'install' failed for 'Bit::Vector'.

**Comment by weekbacker** [comment] 2021-09-16 22:07
OS:  Windows Server 2019
Perl Installation:  strawberry-perl-5.32.1.1-32bit.msi
This is perl 5, version 32, subversion 1 (v5.32.1) built for MSWin32-x64-multi-thread

**Comment by sisyphus** [comment] 2021-09-17 00:01
On Fri, Sep 17, 2021 at 8:07 AM weekbacker ***@***.***> wrote:

> OS: Windows Server 2019
> Perl Installation: strawberry-perl-5.32.1.1-32bit.msi
> This is perl 5, version 32, subversion 1 (v5.32.1) built for
> MSWin32-x64-multi-thread
>

That's somewhat contradictory - a 32-bit msi will not install a (64-bit)
"MSWin32-x64-multi-thread".

The test failure appears to be a permissions issue.
I would just force install anyway.

To sort out the permissions issue I would first cd to the build directory
and run:
perl -Mblib t/51_file_nstore.t

If the same error occurs (as it probably will) then it's time to start
looking at what line 73 is actually doing, and why that action is being
disallowed.

Cheers,
Rob

**Comment by weekbacker** [comment] 2021-09-18 00:22
Thank you, Rob!    I tried the command  perl -Mblib t/51_file_nstore.t
and it errored out at line 94 consistently.   I put in some extra debugging statements to see what was going on and  found that it either quit on a store command or an nstore command:
   store($vector,$file);      <== line 73
   nstore($vector,$file);    <== line 94
I tried getting the latest Storable but that install failed.
I really only need Bit::Vector so that I can install Date::Calc 
but I'm thinking of using Date::ICalc  or   Date::Manip::Calc
instead.    

Probably the store and nstore are geared towards Linux/Unix and Windows has problems with it.

I noticed the t folder was set to readonly so I unchecked the readonly box on the folder and it actually ran longer before it quit but it did quit.  First go around it got to 998 -  then after I unchecked the readonly box it would get up to 2500.   One time it got to 3385.    

Output----
C:\perlsb\cpan\build\Bit-Vector-7.4-4>perl -Mblib t/51_file_nstore.t
1..7083
ok 1
ok 2
ok 3
ok 4
....
....
ok 3383
ok 3384
ok 3385
can't create t/51_file_nstore.tmp: Permission denied at t/51_file_nstore.t line 94.

I wonder if its a Windows OS or Virus detector software that sees all these file stores and decides to shut it down.

 - Jim


-------First-100-lines-of---t/51_file_nstore.t---------------------------
#!perl -w

use strict;
no strict "vars";

$file = $0;
#$file =~ s!^.*[/\\:]+!!;
$file =~ s!\.+[^.]*$!!;
$file .= '.tmp';

eval
{
    require Storable;
    *store    = \&Storable::store;
    *nstore   = \&Storable::nstore;
    *retrieve = \&Storable::retrieve;
};

if ($@ or $Storable::VERSION < 2.21)
{
    print "1..0 # skip module Storable 2.21 or newer not found (we have $Storable::VERSION)\n";
    exit 0;
}

unless (open(TMP, ">$file") and print(TMP "$file\n") and close(TMP) and unlink($file))
{
    print "1..0 # skip cannot write temporary file <$file>: $!\n";
    exit 0;
}

require Bit::Vector;

# ======================================================================

# Determine the size of the nested data structure to be tested in the second part:

$length = 20;

# Create a set of numbers which will represent vector lengths to be tested:

$limit = 4096;

$set = Bit::Vector->new($limit);

$set->Primes();  # Initialize the set with prime numbers (pseudo-random)

$set->Bit_On(0); # Also test special cases with vectors of 0 and 1 bits length
$set->Bit_On(1);

for ( $i = 4; $i-1 < $limit; $i <<= 1 ) # Also test special cases of multiples of two and +/- 1
{
    $set->Bit_On($i-1) if ($i-1 < $limit);
    $set->Bit_On($i)   if ($i   < $limit);
    $set->Bit_On($i+1) if ($i+1 < $limit);
}

$tests = (11 * $set->Norm()) + (30 * $length) - 7; # Determine number of test cases

print "1..$tests\n";

$n = 1;

$start = 0;
while (($start < $set->Size()) &&
  (($min,$max) = $set->Interval_Scan_inc($start)))
{
    $start = $max + 2;
    for ( $bits = $min; $bits <= $max; $bits++ )
    {
        $vector = Bit::Vector->new($bits);
        $vector->Primes();

            print "made it here ccc before store \n";
            print " vector: $vector   \n";
            print " file:   $file     \n";
        store($vector,$file);
            print "made it here ddd after store \n";
        $twin = retrieve($file);
        unlink($file);

        if (ref($twin) eq 'Bit::Vector')
        {print "ok $n\n";} else {print "not ok $n\n";} # 01
        $n++;
        if ($twin->Size() == $bits)
        {print "ok $n\n";} else {print "not ok $n\n";} # 02
        $n++;
        if (${$vector} != ${$twin})
        {print "ok $n\n";} else {print "not ok $n\n";} # 03
        $n++;
        if ($vector->equal($twin))
        {print "ok $n\n";} else {print "not ok $n\n";} # 04
        $n++;

        if ($bits > 0)
        {
            $vector->Flip();
               print "made it here aaa before nstore \n";
               print " vector: $vector   \n";
               print " file:   $file     \n";
            nstore($vector,$file);
               print "made it here bbb after nstore \n";
            $clone = retrieve($file);
            unlink($file);

**Comment by sisyphus** [comment] 2021-09-18 01:28
On Sat, Sep 18, 2021 at 10:23 AM weekbacker ***@***.***>
wrote:

> I wonder if its a Windows OS or Virus detector software that sees all
> these file stores and decides to shut it down.
>
That sounds plausible to me.
If you're able (and willing) to temporarily disable the virus detector
software, I think that could be a useful exercise.

I've just tried installing Bit-Vector-7.4 on Strawberry Perl (64-bit
5.32.0) and it all went fine.
That's on a Windows 7 system.

Being unable to reproduce the problem limits my capacity to be of much
help, I'm afraid.
I took a look at the bug reports at
https://rt.cpan.org/Public/Dist/Display.html?Name=Bit-Vector
and
https://rt.cpan.org/Public/Dist/Display.html?Name=Storable

Nothing stood out to me as being related, and there's nothing there that's
recent.

You aren't the first to experience the issue. At
http://matrix.cpantesters.org/?dist=Bit-Vector%207.4;os=mswin32;reports=1
there are 4 FAIL reports listed on Windows for Bit-Vector-7.4.
Each of those 4 reports experience the same issue as you.

There's a possibility that someone over at perlmonks (
https://www.perlmonks.org/?node=Seekers%20of%20Perl%20Wisdom) might know
more about this issue.

Cheers,
Rob

**Comment by shawnlaffan** [comment] 2023-03-16 05:11
From the discussion in this ticket I would assume the issue lies in the system and not with Strawberry perl.  

FWIW, I can install Bit::Vector on the 5.36 dev version without issue.  

I'll close this issue but please reopen if it can be shown to be a Strawberry perl issue.

**Closed by shawnlaffan** 2023-03-16 05:11 UTC
